import React from "react";

const GetInTouch = () => {
  return (
    <div className="pb-10 text-nowrap overflow-hidden ">
      <p>
        GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GETIN TOUCH GET IN
        TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH
        GET IN TOUCH GET INTOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN
        TOUCH GET IN TOUCH GETIN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH
        GET IN TOUCH
      </p>
      <p>
        GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GETIN TOUCH GET IN
        TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH
        GET IN TOUCH GET INTOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH GET IN
        TOUCH GET IN TOUCH GETIN TOUCH GET IN TOUCH GET IN TOUCH GET IN TOUCH
        GET IN TOUCH
      </p>
    </div>
  );
};

export default GetInTouch;
