import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/src/components/Navbar/NavBar";
import Footer from "@/src/components/Footer/Footer";
import Screen from "@/src/components/screen";
import GetInTouch from "../components/home/GetInTouch";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "univease",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="container ">{children}</div>
        <GetInTouch />
        <Footer />
        <Screen />
      </body>
    </html>
  );
}
